export const metadata = {
  title: "EuroSWift",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="icon"
          type="image/png"
          href="https://img.icons8.com/?size=100&id=hTMPE6ntTofO&format=png&color=000000"
        />
      </head>
      <body>{children}</body>
    </html>
  );
}
